config/routes.rb
Rails.application.routes.draw do
 
  resources :hotels
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :users, only: [:index, :show]

  resources :reservations, only: [:create, :new, :edit, :update, :destroy]
 
  root 'welcome#home'

  resources :users, only: [:show] do 
    resources :reservations, only: [:index, :show]
  end

  get '/all_res', to: 'reservations#all_res'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  #enum role: [:user, :admin]
  has_many :reservations 
  has_many :hotels, through: :reservations 

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  

  def self.from_omniauth(auth)  
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name #I added this
      user.password = Devise.friendly_token[0,20]
    end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  helper_method :sort_column, :sort_direction
  
  def index
    @users = User.all
    unless user_signed_in? && current_user.admin?
      if user_signed_in?
        redirect_to root_path, alert: "Access denied."
      else
        redirect_to new_user_session_path, alert: "Access denied."
      end
    end
  end 

  def show
    @user = User.find(params[:id])
    @reservations = @user.reservations.order(sort_column + " " + sort_direction) #need this for sorting 
  end 

  private

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "check_in"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end



end #ends class  

app/views/users/index.html.erb
<h1 class="hotel-show-title">All users</h1>

<ul id="user-list">
  <% @users.each do |user| %>
    <div>
       <li>Username: <%= user.name %></li> 
       <li>Email: <%= user.email %></li>
       <li><%= link_to "Profile", user_path(user) %> <br> -------------------------------------------------------
       </li>
     </div>
   <% end %>
 </ul>


 <div class="loadMore">Load more</div>

 <script type="text/javascript">

  $(document).ready(function () {
    size_li = $("#user-list li").size();
    x=6;
    $('#user-list li:lt('+x+')').show();
    $('.loadMore').click(function () {
        x = (x+6 <= size_li) ? x+6 : size_li;
        $('#user-list li:lt('+x+')').show();
    });
  });

 </script>

app/views/users/show.html.erb
<% if flash[:alert] %>
  <div class="notice"><%= flash[:alert] %></div>
<% end %>
<!-- allows the alert to show up on the page -->
<div class="profile">
  <h1>Info for: <%= @user.name %></h1>
  <h3>Name: <%= @user.name %></h3>
  <h3>Email: <%= @user.email %></h3>
  <h3>Age: <%= @user.age %> years old</h3>
  <h3>Net Worth: $<%= @user.money %></h3>
</div>
<div class="home-menu">
  <ul>
    <li><%= link_to "Edit Profile", edit_user_registration_path(@user), class:"home-item" %></li>
    <li><%= link_to "Create new reservation", new_reservation_path, class:"home-item" %></li>
    <li><%= link_to "View all my reservations", user_reservations_path(@user), class:"home-item" %></li>
  </ul>
</div>