config/routes.rb
Rails.application.routes.draw do
 
  resources :hotels
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :users, only: [:index, :show]

  resources :reservations, only: [:create, :new, :edit, :update, :destroy]
 
  root 'welcome#home'

  resources :users, only: [:show] do 
    resources :reservations, only: [:index, :show]
  end

  get '/all_res', to: 'reservations#all_res'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :hotel
  belongs_to :user

  has_many :guests, dependent: :destroy
  accepts_nested_attributes_for :guests, allow_destroy: true

end #ends class 

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  load_and_authorize_resource
  helper_method :sort_column, :sort_direction

  def index
    # @reservations = Reservation.order(sort_column + " " + sort_direction)
    @user = User.find(params[:user_id])
    @reservations = @user.reservations.order(sort_column + " " + sort_direction)

    
    unless current_user == @user || current_user.admin?
      redirect_to root_path, alert: "Access denied."
    end
  end 

  def all_res 
    @reservations = Reservation.order(sort_column + " " + sort_direction)
  end

  def show
    @user = User.find(params[:user_id])
    @reservation = @user.reservations.find(params[:id])
  end

  def new
    @reservation = Reservation.new
    # @reservation.guests.build 
  end 

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.hotel_id = params[:hotel_id]
    @reservation.user = current_user
    @hotel = Hotel.find(params[:hotel_id])

    if (@hotel.cost * @reservation.num_nights) > current_user.money 
      flash.now[:notice] = "Sorry, you don't have enough money to stay here"
      render :new  
    elsif @hotel.min_age > current_user.age 
      flash.now[:notice] = "Sorry, you are not old enough to stay here"
      render :new
    elsif @hotel.min_nights > @reservation.num_nights 
      flash.now[:notice] = "Sorry, you need to stay here at least #{@hotel.min_nights} nights" 
      render :new
    elsif @hotel.max_guests < @reservation.num_guests 
      flash.now[:notice] = "Sorry, only a maximum of #{@hotel.max_guests} guests are allowed to stay here"
      render :new
    elsif @reservation.check_in == nil
      flash.now[:notice] = "Please select a valid date"
      render :new 
    elsif @reservation.check_in < Time.now
      flash.now[:notice] = "Please select a valid date"
      render :new 
    else 
      current_user.money -= (@reservation.num_nights * @hotel.cost) 
      current_user.save 
      flash[:alert] = "Thanks for booking a room at #{@hotel.name}!"
      @reservation.save!
      redirect_to user_reservations_path(current_user)
    end 
  end 

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.update(reservation_params)
    @reservation.hotel_id = params[:hotel_id]
    @reservation.user = current_user
    @reservation.save
    redirect_to user_reservation_path(current_user, @reservation)
  end 

  def destroy
    @reservation = Reservation.find(params[:id])
    @hotel = Hotel.find_by_id(@reservation.hotel_id)
    current_user.money += (@reservation.num_nights * @hotel.cost)
    current_user.save
    @reservation.destroy
    flash[:alert] = "Your reservation at #{@hotel.name} has been deleted. You have been refunded $#{@hotel.cost * @reservation.num_nights}"
    if current_user.admin?
      redirect_to all_res_path
    else
      redirect_to user_reservations_path(current_user)
    end
  end 

  private 

  def reservation_params
    params.require(:reservation).permit(:num_nights, :num_guests, :check_in, :hotel_id, guests_attributes: [:id, :name, :_destroy])
  end

  def sort_column
    Reservation.column_names.include?(params[:sort]) ? params[:sort] : "check_in"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end #ends class

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for @reservation do |f| %>

  <%= f.label "Select Hotel" %>
  <%= select_tag :hotel_id, options_from_collection_for_select(Hotel.all, :id, :name, @reservation.hotel_id) %><br><br>

  <%= f.label "Check in date" %>
  <%= f.date_field :check_in %><br><br>

  <%= f.label "Number of nights" %>
  <%= f.number_field :num_nights %><br><br>

  <%= f.label "Number of guests" %>
  <%= f.number_field :num_guests %><br>

  <h3>Guests:</h3>

  <%= f.fields_for :guests do |guest| %>
    <%= render 'guest_fields', f: guest %>
  <% end %>
  <p><%= link_to_add_fields "Add guest", f, :guests %></p>

  
  <%= f.submit %> 

<% end %>

app/views/reservations/_guest_fields.html.erb
<div id="guest_fields">
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", "#", class: "remove_fields" %>
  <br><br>
</div>

app/views/reservations/_guests.html.erb
<fieldset>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/reservations/all_res.html.erb
<h1>All Reservations:</h1>
<h2>Click a title to sort by</h2>
<table id="all-res-table">
  <thead>
  <tr>
    <th><h2><%= sortable "check_in", "Check In Date" %></h2></th>
    <th><h2>&nbsp&nbsp&nbsp<%= sortable "hotel_id", "Hotel" %></h2></th>
    <th><h2><%= sortable "user_id", "Guest" %></h2></th>
  </tr>
  </thead>
  <tbody class="border-bottom">
  <tr>
    <% @reservations.each do |reservation| %>
    <td><br><p class="hotel-text"><%= reservation.try(:check_in).try(:strftime, "%A, %B %d, %Y") %></p></td>
    <td><br><p class="hotel-text">&nbsp&nbsp&nbsp&nbsp&nbsp<%= Hotel.find_by_id(reservation.hotel).name %></p></td>
    <td><br><p class="hotel-text">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= User.find_by_id(reservation.user_id).email %></p></td>
    <td><br>&nbsp&nbsp<%= link_to "View Reservation", user_reservation_path(reservation.user, reservation), class:"crud-opt" %><td>
    <td><br>&nbsp&nbsp<%= link_to "View Guest Profile", user_path(User.find_by_id(reservation.user_id)), class:"crud-opt" %><td>
    <td><br>&nbsp&nbsp<%= link_to "Edit Reservation", edit_reservation_path(reservation), class:"crud-opt" %><td>
    <td><br>&nbsp&nbsp<%= link_to "Delete Reservation", reservation_path(reservation), method: :delete, class:"crud-opt", data: { confirm: 'Are you sure you want to delete this reservation?' } %><td>
  </tr>
  <% end %>
  </tbody>
</table>
<br>

<div class="loadMore">Load more</div>

<script type="text/javascript">
  $(document).ready(function() {
  size_td = $("#all-res-table td").size();
  x=43;
  $('#all-res-table td:lt('+x+')').show();
  $('.loadMore').click(function() {
    x = (x+22 <= size_td) ? x+22 : size_td;
    $('#all-res-table td:lt('+x+')').show();
  });
});
</script>

app/views/reservations/edit.html.erb
<h1>Edit Reservation</h1>

<%= render 'form' %>

app/views/reservations/index.html.erb
<% if flash[:alert] %>
  <div class="notice"><%= flash[:alert] %></div>
<% end %>
<div class="home-menu" id="res-user-menu">
<h1 class="hotel-show-title">All Reservations:</h1>
 <h2>Name: <%= @user.name %></h2>
 <h2>Net Worth: $<%= @user.money %></h2>
 
  <ul>
    <li><%= link_to "Create new reservation", new_reservation_path, class:"home-item" %></li>
  </ul>
 </div>

<table class="index-table" id="res-table">
  <thead>
  <tr>
    <th><h2><%= sortable "check_in", "Check In Date" %></h2></th>
    <th><h2><%= sortable "hotel_id", "Hotel" %></h2></th>
  </tr>
  </thead>
  <tbody class="border-bottom">
  <tr>
    <% @reservations.each do |reservation| %>
    <td><br><p class="hotel-text"><%= reservation.try(:check_in).try(:strftime, "%A, %B %d, %Y") %></p></td>
    <td><br><p class="hotel-text">&nbsp&nbsp&nbsp&nbsp&nbsp<%= Hotel.find_by_id(reservation.hotel_id).name %></p></td>
    
    <td><br>&nbsp&nbsp<%= link_to "View Reservation", user_reservation_path(@user, reservation), class:"crud-opt" %><td>
    <td><br>&nbsp&nbsp<%= link_to "Edit Reservation", edit_reservation_path(reservation), class:"crud-opt" %><td>
    <td><br>&nbsp&nbsp<%= link_to "Delete Reservation", reservation_path(reservation), class:"crud-opt", method: :delete, data: { confirm: 'Are you sure you want to delete this reservation?' } %><td>
  </tr>
  <% end %>
  </tbody>
</table>

<div class="loadMore">Load more</div>

<script type="text/javascript">
  $(document).ready(function() {
  size_td = $("#res-table td").size();
  x=15;
  $('#res-table td:lt('+x+')').show();
  $('.loadMore').click(function() {
    x = (x+16 <= size_td) ? x+16 : size_td;
    $('#res-table td:lt('+x+')').show();
  });
});
</script>

app/views/reservations/new.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<%= render 'form' %>

app/views/reservations/show.html.erb
<h1>Reservation:</h1>

<h2>Guest: <%= User.find_by_id(@reservation.user_id).email %></h2>
<h2>Hotel: <%= Hotel.find_by_id(@reservation.hotel_id).name %></h2>
<h3>Check In Date: <%= @reservation.try(:check_in).try(:strftime, "%A, %B %d, %Y") %></h3>
<h3>Price per night: $<%= Hotel.find_by_id(@reservation.hotel_id).cost %></h3>
<h3>Number of nights: <%= @reservation.num_nights %></h3>
<h3>Number of guests: <%= @reservation.num_guests %></h3>
<ul>
<% for guest in @reservation.guests %>
<li><%= guest.name %></li>
<% end %>
</ul>

<h3>Total Cost: $<%= @reservation.num_nights * Hotel.find_by_id(@reservation.hotel_id).cost %></h3>

<%= link_to "Edit Reservation", edit_reservation_path(@reservation), class:"crud-opt" %> 

<%= link_to "Delete Reservation", reservation_path(@reservation), class:"crud-opt", method: :delete, data: { confirm: 'Are you sure you want to delete this reservation?' } %> 

<%= link_to 'View All Reservations',user_reservations_path(current_user), class:"crud-opt" %>