config/routes.rb
Rails.application.routes.draw do
 
  resources :hotels
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :users, only: [:index, :show]

  resources :reservations, only: [:create, :new, :edit, :update, :destroy]
 
  root 'welcome#home'

  resources :users, only: [:show] do 
    resources :reservations, only: [:index, :show]
  end

  get '/all_res', to: 'reservations#all_res'

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  has_many :reservations
  has_many :users, through: :reservations
  has_attached_file :avatar, styles: { thumb: "300x300>", show: "500x500>" }, :default_url => "default_thumb.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :name, presence: true
  validates :cost, presence: true
  validates_length_of :phone_number, :within => 10..12
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  load_and_authorize_resource
  helper_method :sort_column, :sort_direction

  def index #view all hotels
    @hotels = Hotel.order(sort_column + " " + sort_direction).page(params[:page])
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @hotels }
    end
   
    unless user_signed_in? 
      redirect_to new_user_session_path, alert: "Access denied."
    end
  end 

  def show #view a single hotel 
    @hotel = Hotel.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @hotel }
    end
  end 

  def new
    @hotel = Hotel.new
  end 

  def create 
    @hotel = Hotel.create(hotel_params)
    render json: @hotel, status: 201
    # redirect_to hotel_path(@hotel) 
  end 

  def edit 
    @hotel = Hotel.find(params[:id])
  end 

  def update 
    @hotel = Hotel.find(params[:id])
    @hotel.update(hotel_params)
    redirect_to hotel_path(@hotel)
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
    flash[:alert] = "#{@hotel.name} has been deleted"
    redirect_to hotels_path
  end 

  private 

  def hotel_params 
    params.require(:hotel).permit(:name, :avatar, :cost, :min_age, :min_nights, :max_guests, :address, :phone_number)
  end 

  def sort_column
    Hotel.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end


end #ends class 

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_hotel.html.erb
<%= form_for @hotel, html: {multipart: true} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br><br>

  <%= f.label :avatar %>
  <%= f.file_field :avatar %> <br><br>

  <%= f.label "Phone Number:" %>
  <%= f.text_field :phone_number %> <br><br>

  <%= f.label :address %>
  <%= f.text_field :address %> <br><br>

  <%= f.label :cost %>
  <%= f.number_field :cost %> <br><br>

  <%= f.label "Minimum age to stay here" %>
  <%= f.number_field :min_age %><br><br>

  <%= f.label "Minimum number of nights" %>
  <%= f.number_field :min_nights %> <br><br>

  <%= f.label "Maximum number of guests" %>
  <%= f.number_field :max_guests %><br><br> 

  <%= f.submit  %>

<% end %>

app/views/hotels/edit.html.erb
<h1>Edit Hotel</h1>


<%= render 'hotel' %>
  

app/views/hotels/index.html.erb
<div class="page-menu">
  <ul>
    <% if current_user.admin? %>
      <li><%= link_to "Create a new Hotel", new_hotel_path, class:"page_menu_text" %></li>
    <% end %>
    <% if user_signed_in? || current_user.admin? %>
      <li><%= link_to "Make a new reservation", new_reservation_path, class:"page_menu_text" %></li>
    <% end %>
  </ul>
</div>

  <p class="hotel-show-title">All Hotels:</p>


<div class="container">
<%= page_entries_info @hotels %>
<%= paginate @hotels, window: 2 %>


<table id="index_table">
  <thead> 
    <tr>
      <th><%= sortable "name", "Hotel" %></th>
      <th>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= sortable "cost", "Price per night" %></th>
    </tr>
  </thead>
  
  <tbody class="border-bottom">
    <tr>
    <% @hotels.each do |hotel| %>
  
      <td><%= image_tag hotel.avatar.url(:thumb), class: "hotel_image" %></td>
      <td><br><p class="hotel-text">&nbsp&nbsp<%= hotel.name %></p></td>
      <td><br><p class="hotel-text">&nbsp&nbsp&nbsp&nbsp&nbsp$<%= hotel.cost %> per night</p></td>
      <td><br>&nbsp&nbsp&nbsp&nbsp&nbsp<%= link_to "Details", hotel_path(hotel), class:"crud-opt" %></td>
      <% if current_user.admin? %>
        <td><br>&nbsp&nbsp&nbsp&nbsp&nbsp<%= link_to "Delete hotel", hotel_path(hotel), class:"crud-opt", method: :delete, data: { confirm: 'Are you sure you want to delete this hotel?' } %></td>

      <% end %>
    </tr>
    <% end %>
  </tbody>

</table>
</div> 

app/views/hotels/new.html.erb
<div class="page-menu">
  <%= link_to "View All Hotels", hotels_path, class:"page_menu_text" %> <br><br>
  <h1>Create a new hotel</h1>
</div>

<br><br><br>

<%= render 'hotel' %>


<div id="hotelResult">
  <h2 id="hotelName"></h2>
  <p id="hotelPhone"></p>
  <p id="hotelAddress"></p>
  <p id="hotelCost"></p>
  <p id="hotelAge"></p>
  <p id="hotelNights"></p>
  <p id="hotelGuests"></p>
 
</div>

<!-- How can I get my image to show up here? -->
<script type="text/javascript" charset="utf-8">
  $(function() { 
  $('form').submit(function(event) {
    event.preventDefault();

    var values = $(this).serialize();

    var posting = $.post('/hotels', values);

    posting.done(function(data) {
      var hotel = data["hotel"];
      $("#hotelName").text(hotel["name"]);
      $("#hotelPhone").text(hotel["phone_number"]);
      $("#hotelAddress").text(hotel["address"]);
      $("#hotelCost").text(hotel["cost"]).val();
      $("#hotelAge").text(hotel["min_age"]).val();
      $("#hotelNights").text(hotel["min_nights"]).val();
      $("#hotelGuests").text(hotel["max_guests"]).val();
    });
   });
  });

</script>

app/views/hotels/show.html.erb
<div class="page-menu">
<ul>
<li><%= link_to "View all hotels", hotels_path, class:"page_menu_text" %></li>
<li><%= link_to "Edit Hotel", edit_hotel_path(@hotel), class:"page_menu_text" %></li>
</ul>
</div>

<p class="hotel-show-title"><%= @hotel.name %></p>
<div class="container">
  <div id="contact">
    <h2>Contact Information:</h2>
    <h3>Phone Number: <%= @hotel.phone_number %></h3>
    <h3>Address: <%= @hotel.address %></h3>
    <br>
    <h2>Hotel Details:</h2>
    <h3>Price per night: $<%= @hotel.cost %> </h3>
    <h3>Minimum Night Stay: <%= @hotel.min_nights %></h3>
    <h3>Maximum people per room: <%= @hotel.max_guests %></h3>
    <h3>Minimum age to book a reservation: <%= @hotel.min_age %> years old</h3>
  </div>


  <div id="show-image"><%= image_tag @hotel.avatar.url(:show) %><div>

</div>